# -*- coding: utf-8 -*-
"""teststreamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gfo1Ls-bS7pnlGtByZ1wX5LUslvdh-7A
"""

!pip install streamlit

!pip install pyngrok==4.1.1
from pyngrok import ngrok

public_url = ngrok.connect(port='8501')
public_url

import streamlit as st

st.title('Testing Streamlit App')
st.write('Welcome to my app!')

!streamlit run --server.port 80 teststreamlit.py >/dev/null

import streamlit as st
import pandas as pd
import altair as alt

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("Study Case - Dataset VIX Dummy - Data for Study Case 1.csv")

df['first_contact'] = pd.to_datetime(df['first_contact'])
df['checkout_date'] = pd.to_datetime(df['checkout_date'])
df['paid_date'] = pd.to_datetime(df['paid_date'])

purchases_by_date = df.groupby('checkout_date').size().reset_index(name='count')

# Create a line chart using Altair
chart = alt.Chart(purchases_by_date).mark_line().encode(
    x='checkout_date:T',
    y='count:Q'
).properties(
    width=800,
    height=400
)

# Display the chart using Streamlit
st.altair_chart(chart)

